/**
 * Install the squad coordination hooks as an omp-DISCOVERED extension.
 *
 * omp auto-loads `~/.omp/agent/extensions/<name>/index.ts` (each a module with
 * `export default function(pi: ExtensionAPI)`) into EVERY session — raw or
 * squad. We drop a tiny generated shim there that re-exports BOTH of this
 * repo's hooks by absolute path, so a plain `omp` session also claims file
 * leases on edit and warns when another session already holds the file. No
 * per-invocation `-e` flag, no edits to omp config — register once.
 *
 *   bun src/install-hooks.ts             # install
 *   bun src/install-hooks.ts --uninstall # remove
 *
 * ponytail: this is a generated shim that re-exports the repo's two hooks by
 * ABSOLUTE path — re-run after moving the repo (the embedded paths go stale).
 * The lease-hook stays advisory: it warns once per file per session, never a
 * hard lock.
 */

import * as fsp from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";

const EXT_NAME = "omp-squad-coord";

/** Where omp discovers extensions. The env override exists only for tests. */
export function extensionsDir(): string {
	return process.env.OMP_EXT_DIR || path.join(os.homedir(), ".omp", "agent", "extensions");
}

/** Text of the discovered-extension index.ts: re-exports both hooks by absolute path. */
export function shimContent(repoSrc: string): string {
	const presence = JSON.stringify(path.join(repoSrc, "presence-hook.ts"));
	const lease = JSON.stringify(path.join(repoSrc, "lease-hook.ts"));
	return `// AUTO-GENERATED by \`bun src/install-hooks.ts\` — re-run if the repo moves.
import type { ExtensionAPI } from "@oh-my-pi/pi-coding-agent";
import presenceHook from ${presence};
import leaseHook from ${lease};
export default function ompSquadCoord(pi: ExtensionAPI): void {
\tpresenceHook(pi);
\tleaseHook(pi);
}
`;
}

/** Write the shim into `<dir>/<EXT_NAME>/index.ts`; return the written path. */
export async function install(repoSrc: string, dir = extensionsDir()): Promise<string> {
	const extDir = path.join(dir, EXT_NAME);
	await fsp.mkdir(extDir, { recursive: true });
	const file = path.join(extDir, "index.ts");
	await fsp.writeFile(file, shimContent(repoSrc));
	return file;
}

/** Best-effort removal of the installed extension dir.
 *  @substrate the installer's reversal primitive — no CLI wiring yet (named gap, not hidden);
 *  exercised directly by tests/install-hooks.test.ts. */
export async function uninstall(dir = extensionsDir()): Promise<boolean> {
	await fsp.rm(path.join(dir, EXT_NAME), { recursive: true, force: true }).catch(() => {});
	return true;
}

if (import.meta.main) {
	try {
		if (process.argv.includes("--uninstall")) {
			await uninstall();
			process.stdout.write(`removed ${path.join(extensionsDir(), EXT_NAME)}\n`);
		} else {
			// This file lives in src/; the hooks are siblings.
			const file = await install(import.meta.dir);
			process.stdout.write(`installed ${file}\n`);
			process.stdout.write("every NEW omp session now joins squad presence + file-lease coordination.\n");
			process.stdout.write("running omp sessions must be restarted to pick it up.\n");
		}
	} catch (err) {
		process.stderr.write(`omp-squad coord install failed: ${err instanceof Error ? err.message : String(err)}\n`);
		process.exitCode = 1;
	}
}
